aid: 127001
aid_replace_open: false
api_assesskey_open:
  '1': false
  '2': false
  '3': false
  '4': false
appsearch_remake: {}
area_cache_open: true
blacklist_config: !MixedBlackList
  api: https://black.qimo.ink/api/users/
  api_version: 2
block_bangumi_ep: []
block_bangumi_cid: []
block_bangumi_avid: []
block_bangumi_bvid: []
cache:
  '-10403': 6480
  '-404': 1380
  '-412': 1380
  '0': 6480
  'other': 1380
  'thsub': 14400
cn_app_playurl_api: https://api.bilibili.com/pgc/player/api/playurl
cn_app_search_api: https://app.bilibili.com/x/v2/search/type
cn_proxy_accesskey_open: false
cn_proxy_accesskey_url: ''
cn_proxy_playurl_open: false
cn_proxy_playurl_url: '127.0.0.1:7890'
cn_proxy_search_open: false
cn_proxy_search_url: '127.0.0.1:7890'
cn_proxy_token_open: false
cn_proxy_token_url: '127.0.0.1:7890'
cn_web_playurl_api: https://api.bilibili.com/pgc/player/web/playurl
cn_web_search_api: https://api.bilibili.com/x/web-interface/search/type
config_version: 4
donate_url: https://afdian.net/@***
general_api_bilibili_com_proxy_api: api.bilibili.com
general_app_bilibili_com_proxy_api: app.bilibili.com
hk_app_playurl_api: https://api.bilibili.com/pgc/player/api/playurl
hk_app_search_api: https://app.bilibili.com/x/v2/search/type
hk_proxy_playurl_open: false
hk_proxy_playurl_url: '127.0.0.1:7890'
hk_proxy_search_open: false
hk_proxy_search_url: '127.0.0.1:7890'
hk_web_playurl_api: https://api.bilibili.com/pgc/player/web/playurl
hk_web_search_api: https://api.bilibili.com/x/web-interface/search/type
http2https_support: false
http_port: 2662
https_port: 443
https_support: false
limit_biliroaming_version_max: 80
limit_biliroaming_version_min: 64
limit_biliroaming_version_open: false
local_wblist:
  '114514':
    - false
    - false
trusted_proxies: []
rate_limit_burst: 20
rate_limit_per_second: 3
redis: 'redis://:password@host:6379'
report_config: !TgBot
  tg_bot_token: ''
  tg_chat_id: ''
  tg_proxy_api_open: false
  tg_proxy_url: ''
report_open: false
resign_api:
  '1': ''
  '2': ''
  '3': ''
  '4': ''
resign_api_sign:
  '1': ''
  '2': ''
  '3': ''
  '4': ''
resign_from_api_open:
  '1': false
  '2': false
  '3': false
  '4': false
resign_from_existed_key: false
resign_open:
  '1': false
  '2': false
  '3': false
  '4': false
resign_pub:
  '1': false
  '2': false
  '3': false
  '4': false
th_app_playurl_api: https://app.biliintl.com/intl/gateway/v2/ogv/playurl
th_app_search_api: https://app.biliintl.com/intl/gateway/v2/app/search/type
th_app_season_api: https://app.biliintl.com/intl/gateway/v2/ogv/view/app/season
th_app_season_sub_api: 'https://example.com/?season_id='
th_app_season_sub_name: 示例字幕组
th_app_season_sub_open: false
th_proxy_playurl_open: false
th_proxy_playurl_url: '127.0.0.1:7890'
th_proxy_search_open: false
th_proxy_search_url: '127.0.0.1:7890'
th_proxy_subtitle_open: false
th_proxy_subtitle_url: '127.0.0.1:7890'
th_proxy_token_open: false
th_proxy_token_url: '127.0.0.1:7890'
th_web_playurl_api: https://app.biliintl.com/intl/gateway/v2/ogv/playurl
th_web_search_api: https://app.biliintl.com/intl/gateway/v2/app/search/type
tw_app_playurl_api: https://api.bilibili.com/pgc/player/api/playurl
tw_app_search_api: https://app.bilibili.com/x/v2/search/type
tw_proxy_playurl_open: false
tw_proxy_playurl_url: '127.0.0.1:7890'
tw_proxy_search_open: false
tw_proxy_search_url: '127.0.0.1:7890'
tw_web_playurl_api: https://api.bilibili.com/pgc/player/web/playurl
tw_web_search_api: https://api.bilibili.com/x/web-interface/search/type
websearch_remake: {}
worker_num: 8
